### PR TITLE
Hektor

### PR DESCRIPTION
**Pull request by Lokathor**

### CODE REVIEW

**Comment by Lokathor** [comment]
So this is targeting the `euclid` library branch like you said, not sure why it thinks commits from icefox are part of this, but i guess i forked from `master` and maybe they're not in that branch or something.

**Comment by bitshifter** [comment]
Cool, I'm on vacation until next week, will merge it in when I get back.

**Comment by Lokathor** [comment]
quat*vec3 is also currently missing because hektor doesn't do that yet, but I'll put it in as another PR later on, so you can merge this whenever vacation is over

**Comment by bitshifter** [comment]
I've merged the euclid support to master so you might need to update this PR to be against master. Hopefully that is straight forward, sorry for the inconvenience.

**Comment by Lokathor** [comment]
Uh, not sure how to do that even. I'll just close this for now and then make a fresh PR when I get the time

**Pull request closed without merging**
